package com.gr.common.rest.messagebox.constants;

public enum ServiceName {
    ACCOUNT_SERVICE, TRAVEL_DATA_ANALYZER_SERVICE, INTELL_SERVICE, REFERENCEDATA_SERVICE, TRAVEL_DATA_GATEWAY, EXTERNAL, SYNC_SERVICE, COMM_SERVICE
}
